name: CheckAndBuild

on:
  schedule:
    - cron: "0 7 1 * *"
  push:

jobs:
  CheckAndBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node-version }}"
      - name: "check and build"
        run: |
          npm install -D npm-check-updates
          npx ncu -u
          webpack
      - env:
          CI: true
        name: "repositry push"
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "profsend_source-CI"
          git config user.email "gutsmine910@gmail.com"
          git remote set-url origin https://gumieprof:${{ secrets.GITHUB_PASS }}@github.com/gumieProf/profsend-source
          git branch
          git checkout main
          git branch
          date >> CItime.md
          git add .
          git commit -m "[CI]Vulnerability check ok"
          git push origin main
      - if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          git config user.name "profsend_source-CI"
          git config user.email "gutsmine910@gmail.com"
          git remote set-url origin https://gumieprof:${{ secrets.GITHUB_PASS }}@github.com/gumieProf/profsend-source
          git branch
          git checkout dev
          git branch
          date >> CItime.md
          git add .
          git commit -m "[CI]Vulnerability check ok"
          git push origin dev
